### ISSUE TITLE
[Question] Should I create document for each action?

### ISSUE THREAD

**Issue by mahmoud-syr** [simplify9/Infolink#10]
_First of all I'd like to sincerely apologize if questions are not supposed to be posted here as issues, please do let me know if that's the case._
I have a question related to the logic/concepts behind Infolink system:
If I have a controller called 'Agent' where there are ridiculous amount of actions for example (create shipment, update shipment, create manifest, update manifest, create master airwaybill, update master airwaybill ...etc.), should I create separate document for each action?

Thanks very much in advance.

**Comment by samerzughul** [comment]
Yes, we recommend creating a document for each action in order to expose a separate endpoint for each one of them with its own subscriptions (validators, mappers, and handlers) for each partner.
