### ISSUE TITLE
How I can add Validators and Mappers and Handlers

### ISSUE THREAD

**Issue by srss1985** [simplify9/Infolink#48]
Hi All,
I tried the info link project to create a routing module and I created a document and partners and subscribers, I want to ask how I can add the validators, mapper and handler class to this API to I can use the validations as a sample.
thank you in advance if you can share with me some sample or explain it to me.
![InfoLink](https://user-images.githubusercontent.com/34206823/209848071-afe10cba-ed3d-4975-8340-5ac0e2ef2104.png)

**Comment by samerzughul** [comment]
Hi @srss1985, in order to set validators, mappers or handlers, you need to add them to the storage account being consumed by infolink (S3/azure storage), Infolink will list the available ones, you can check these reusable adapters repo as an example https://github.com/simplify9/InfolinkAdapters 
i will draft a small doc outlining the needed step to create an adapter and deploy it

**Comment by srss1985** [comment]
Thank you for your quick response, I will try and wait for your document, I want to do a full cycle.

**Comment by MohammedWaheeb** [comment]
Dear @srss1985 Please check the updated documentation at https://github.com/simplify9/Infolink#how-to-install-serverless-adapters 
And feel free to reach out to us if you have any other questions

**Comment by srss1985** [comment]
Hi Mohammad,

Thank you for sharing the document, I tried from my side but still may I have something missing.
I used this command to register : 
dotnet serverless.dll @( -p "s3" -a "Access Key" -s "Secret Key" -b "infolink" -u "http://localhost:9000/]" "console csproj path")

But still not working for me, I created a console app same as the below screenshot:
![image](https://user-images.githubusercontent.com/34206823/213148837-82f61c98-3d43-434c-92af-f0a57b798faf.png)

and another question: what is the difference between xchange & xchange_result

Thank you for your support

**Comment by MohammedWaheeb** [comment]
Dear Ahmad http://localhost:9000/ needs to be the URL of the s3 bucket not localhost
*we support azure storage too

**Comment by srss1985** [comment]
Dear Mohammad,

Just to understand this URL for my local Minio that I used to configure the handlers, mappers, and validators on it,
Please correct me if  I have misunderstood and if it's wrong, what should I do?

and please what is the difference between xchange & xchange_result entities?

Thank you.

**Comment by MohammedWaheeb** [comment]
Dear Ahmad
the args should start with the path to the csproj followed by the name of the adapter 

csproj path 
Infolink6.handlers.name
-a
"Access Key"
-s
"Secret Key" 
-b
infolink
-u
 http://localhost:9000/

The xchange entity is the basic entity for any action in infolink it holds the base data and it has a relationship with xchange_result which contains the output of the xchanges
