### ISSUE TITLE
Bug: Cannot open the dashboard

### ISSUE THREAD

**Issue by mahmoud-syr** [simplify9/Infolink#8]
I was trying to send an `HttpRequest` through info link to `Google.com` as a test. I created a document first called `Shipment Types` and then created a partner `(Mahmoud_Test)` and added credentials but here I didn't notice the `Save` button in the top of the page (which is really not the best user experience IMHO) I tried to hit the API with an http request (mistakingly get request) and then (post request) I kept getting `Unauthorized request` until I noticed that I have to click save, so I get back to the partner page, re-created the credentials and clicked `Save`. I sent the `HttpRequest` successfully. I tried to get to the dashboard to see the logs but I couldn't open the dashboard.
The following is an image to the error I'm getting:

![image](https://user-images.githubusercontent.com/65822550/94574990-09def280-0274-11eb-81e8-7d3c5dcc5a2f.png)

**Comment by awajan** [comment]
It appears, there is an issue with RabbitMq. Infolink depends on RabbitMq to do processing of incoming requests. Have you completed RabbitMq setup and connecting it to Infolink?

Also, I noticed the document name has a space, it is not recommended, since this is part of a url.

**Comment by mahmoud-syr** [comment]
> It appears, there is an issue with RabbitMq. Infolink depends on RabbitMq to do processing of incoming requests. Have you completed RabbitMq setup and connecting it to Infolink?
> 
> Also, I noticed the document name has a space, it is not recommended, since this is part of a url.

I was testing on the hosted domain (sf9) not locally on my machine

**Comment by awajan** [comment]
Ok, the RabbitMq server was down as we are running the free tier from cloudamqp.com. It should be ok now.

**Comment by mahmoud-syr** [comment]
Thank you very much for your quick reply
