### ISSUE TITLE
[Question] Cannot run InfoLink project locally Value cannot be null. (Parameter 'uriString')

### ISSUE THREAD

**Issue by mahmoud-syr** [simplify9/Infolink#9]
I'm trying to run Infolink project locally but I'm getting a null exception, I traced it and I think it has something to do with `InfolinkClientOptions` the `InfolinkClient` configuration section. Is it a required configuration section in the web application main project? what should be there?
Also, I have another question: `services.AddCloudFiles();` is this service a requirement for the functionality of the project? I commented this line because I do not have amazon cloud services account, I just want to try to send post request to local web-api project through Infolink.

Thanks a lot.

**Comment by samerzughul** [comment]
Infolink client is used by the UI to call its APIs. Its options include the APIs base URL.

As for the cloud files service, it is needed for infolink to function, but you can use any S3 compatible storage.

Here is the schema of the appsettings needed for the app to function.
{
    "ASPNETCORE_ENVIRONMENT":"",
    "DatabaseType": "MySql",
    "SwLogger":{
        "ApplicationName": "",
        "ElasticsearchUrl": "",
        "ElasticsearchUser": "",
        "ElasticsearchPassword": ""
    },
    "InfolinkClient":{
        "BaseUrl":" http(s)://{{Base url}}/cqapi/"
    },
    "CloudFiles": {
        "AccessKeyId": ""
        "SecretAccessKey": "",
        "ServiceUrl": "",
        "BucketName": ""
    },
    "ConnectionStrings":{
        "InfolinkDb: "",
        "RabbitMQ": ""
    },
    "Token": {
        "Key": "",
        "Issuer": "",
        "Audience": ""
    }
}
